#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Tomcat.
# Description:       Start the Tomcat servlet engine.
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
NAME=harctoolbox
DESC="Harctoolbox daemon"
         
#JAVA_HOME=/opt/jdk1.6.0_14
#JRE_HOME=$JAVA_HOME
#export JAVA_HOME
#export JRE_HOME

if [ -r /etc/default/locale ]; then
	. /etc/default/locale
	export LANG
fi

# FIXME
TZ=CET; export TZ

case "$1" in
  start)
	harctoolbox -P -l -w /usr/local/share/harctoolbox/tasks.xml 1> /var/log/harctoolboxd 2>&1  &
	dispatcher &
	;;
  stop)
	kill `cat /var/run/harctoolbox.pid`
	kill `cat /var/run/dispatcher.pid`
	;;
  *)
	echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
